packages:
  - "apps/*"
  - "packages/*"

verifyDepsBeforeRun: false
confirmModulesPurge: false

onlyBuiltDependencies:
  - "@prisma/engines"
  - "@swc/core"
  - "bcrypt"
  - "esbuild"
  - "prisma"
  - "sharp"
  - "unrs-resolver"

ignoredBuiltDependencies:
  - "@scarf/scarf"

overrides:
  "@hono/node-server": "1.19.13"
  "@nestjs/swagger@11.4.6>js-yaml": "5.2.3"
  "fast-uri": "3.1.5"
  "multer": "2.2.0"
